=== api-evangelist/gitlab/json-schema/gitlab-openapi-original-api_entities_commit-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/gitlab/refs/heads/main/json-schema/gitlab-openapi-original-api_entities_commit-schema.json",
  "title": "API_Entities_Commit",
  "description": "API_Entities_Commit from GitLab API",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "example": "2695effb5807a22ff3d138d593fd856244e155e7"
    },
    "short_id": {
      "type": "string",
      "example": "2695effb"
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "example": "2017-07-26 09:08:53+00:00"
    },
    "parent_ids": {
      "type": "array",
      "items": {
        "type": "string",
        "example": "2a4b78934375d7f53875269ffd4f45fd83a84ebe"
      }
    },
    "title": {
      "type": "string",
      "example": "Initial commit"
    },
    "message": {
      "type": "string",
      "example": "Initial commit"
    },
    "author_name": {
      "type": "string",
      "example": "John Smith"
    },
    "author_email": {
      "type": "string",
      "example": "john@example.com"
    },
    "authored_date": {
      "type": "string",
      "format": "date-time",
      "example": "2012-05-28 11:42:42+00:00"
    },
    "committer_name": {
      "type": "string",
      "example": "Jack Smith"
    },
    "committer_email": {
      "type": "string",
      "example": "jack@example.com"
    },
    "committed_date": {
      "type": "string",
      "format": "date-time",
      "example": "2012-05-28 11:42:42+00:00"
    },
    "trailers": {
      "type": "object",
      "properties": {},
      "example": "{ \"Merged-By\": \"Jane Doe janedoe@gitlab.com\" }"
    },
    "web_url": {
      "type": "string",
      "example": "https://gitlab.example.com/janedoe/gitlab-foss/-/commit/ed899a2f4b50b4370feeea94676502b42383c746"
    }
  }
}

=== api-evangelist/gitlab/examples/gitlab-openapi-original-api_entities_commit-example.json
{
  "id": "2695effb5807a22ff3d138d593fd856244e155e7",
  "short_id": "2695effb",
  "created_at": "2017-07-26 09:08:53+00:00",
  "parent_ids": [
    "2a4b78934375d7f53875269ffd4f45fd83a84ebe"
  ],
  "title": "Initial commit",
  "message": "Initial commit",
  "author_name": "John Smith",
  "author_email": "john@example.com",
  "authored_date": "2012-05-28 11:42:42+00:00",
  "committer_name": "Jack Smith"
}
