=== api-evangelist/gitlab/json-schema/gitlab-api-entities-plan-limit-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/gitlab/main/json-schema/gitlab-api-entities-plan-limit-schema.json",
  "title": "API_Entities_PlanLimit",
  "description": "API_Entities_PlanLimit model",
  "x-generated": "2026-10-04",
  "x-method": "derived",
  "x-generator": "derive-json-schema.py",
  "x-source": "openapi/gitlab-application-api-openapi.yml#/components/schemas/API_Entities_PlanLimit",
  "type": "object",
  "properties": {
    "ci_pipeline_size": {
      "type": "integer",
      "format": "int32"
    },
    "ci_active_jobs": {
      "type": "integer",
      "format": "int32"
    },
    "ci_project_subscriptions": {
      "type": "integer",
      "format": "int32"
    },
    "ci_pipeline_schedules": {
      "type": "integer",
      "format": "int32"
    },
    "ci_needs_size_limit": {
      "type": "integer",
      "format": "int32"
    },
    "ci_registered_group_runners": {
      "type": "integer",
      "format": "int32"
    },
    "ci_registered_project_runners": {
      "type": "integer",
      "format": "int32"
    },
    "conan_max_file_size": {
      "type": "integer",
      "format": "int32"
    },
    "enforcement_limit": {
      "type": "integer",
      "format": "int32"
    },
    "generic_packages_max_file_size": {
      "type": "integer",
      "format": "int32"
    },
    "helm_max_file_size": {
      "type": "integer",
      "format": "int32"
    },
    "limits_history": {
      "type": "object",
      "properties": {}
    },
    "maven_max_file_size": {
      "type": "integer",
      "format": "int32"
    },
    "notification_limit": {
      "type": "integer",
      "format": "int32"
    },
    "npm_max_file_size": {
      "type": "integer",
      "format": "int32"
    },
    "nuget_max_file_size": {
      "type": "integer",
      "format": "int32"
    },
    "pipeline_hierarchy_size": {
      "type": "integer",
      "format": "int32"
    },
    "pypi_max_file_size": {
      "type": "integer",
      "format": "int32"
    },
    "terraform_module_max_file_size": {
      "type": "integer",
      "format": "int32"
    },
    "storage_size_limit": {
      "type": "integer",
      "format": "int32"
    }
  }
}

=== api-evangelist/gitlab/examples/gitlab-api-v4-application-api_entities_plan-limit-example.json
{
  "ci_pipeline_size": 0,
  "ci_active_jobs": 0,
  "ci_project_subscriptions": 2,
  "ci_pipeline_schedules": 10,
  "ci_needs_size_limit": 50,
  "ci_registered_group_runners": 1000,
  "ci_registered_project_runners": 1000,
  "conan_max_file_size": 3221225472,
  "enforcement_limit": 15000,
  "generic_packages_max_file_size": 5368709120
}
