=== api-evangelist/gitlab/json-schema/gitlab-api-v4-groups-api_entities_access-requester-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/gitlab/refs/heads/main/json-schema/gitlab-api-v4-groups-api_entities_access-requester-schema.json",
  "title": "API_Entities_AccessRequester",
  "description": "API_Entities_AccessRequester model",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int32",
      "example": 1
    },
    "username": {
      "type": "string",
      "example": "admin"
    },
    "name": {
      "type": "string",
      "example": "Administrator"
    },
    "state": {
      "type": "string",
      "example": "active"
    },
    "avatar_url": {
      "type": "string",
      "example": "https://gravatar.com/avatar/1"
    },
    "avatar_path": {
      "type": "string",
      "example": "/user/avatar/28/The-Big-Lebowski-400-400.png"
    },
    "custom_attributes": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/API_Entities_CustomAttribute"
      }
    },
    "web_url": {
      "type": "string",
      "example": "https://gitlab.example.com/root"
    },
    "email": {
      "type": "string",
      "example": "user@example.com"
    },
    "requested_at": {
      "type": "string",
      "example": "2026-04-17T12:00:00Z"
    }
  }
}

=== api-evangelist/gitlab/examples/gitlab-openapi-original-api_entities_access-requester-example.json
{
  "id": 1,
  "username": "admin",
  "name": "Administrator",
  "state": "active",
  "avatar_url": "https://gravatar.com/avatar/1",
  "avatar_path": "/user/avatar/28/The-Big-Lebowski-400-400.png",
  "custom_attributes": [
    "2026-04-17T12:00:00Z"
  ],
  "web_url": "https://gitlab.example.com/root",
  "email": "user@example.com",
  "requested_at": "2026-04-17T12:00:00Z"
}
