=== api-evangelist/gitlab/json-schema/gitlab-api-entities-broadcast-message-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/gitlab/main/json-schema/gitlab-api-entities-broadcast-message-schema.json",
  "title": "API_Entities_BroadcastMessage",
  "description": "API_Entities_BroadcastMessage model",
  "x-generated": "2026-10-04",
  "x-method": "derived",
  "x-generator": "derive-json-schema.py",
  "x-source": "openapi/gitlab-broadcast-messages-api-openapi.yml#/components/schemas/API_Entities_BroadcastMessage",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "starts_at": {
      "type": "string"
    },
    "ends_at": {
      "type": "string"
    },
    "color": {
      "type": "string"
    },
    "font": {
      "type": "string"
    },
    "target_access_levels": {
      "type": "string"
    },
    "target_path": {
      "type": "string"
    },
    "broadcast_type": {
      "type": "string"
    },
    "dismissable": {
      "type": "string"
    },
    "active": {
      "type": "string"
    }
  }
}

=== api-evangelist/gitlab/examples/gitlab-api-v4-broadcast-messages-api_entities_broadcast-message-example.json
{
  "id": "123456",
  "message": "example_value",
  "starts_at": "2026-04-17T12:00:00Z",
  "ends_at": "2026-04-17T12:00:00Z",
  "color": "example_value",
  "font": "example_value",
  "target_access_levels": "example_value",
  "target_path": "my-group/my-project",
  "broadcast_type": "example_value",
  "dismissable": "example_value"
}
