=== api-evangelist/gitlab/json-schema/gitlab-api-entities-appearance-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/gitlab/main/json-schema/gitlab-api-entities-appearance-schema.json",
  "title": "API_Entities_Appearance",
  "description": "API_Entities_Appearance model",
  "x-generated": "2026-10-04",
  "x-method": "derived",
  "x-generator": "derive-json-schema.py",
  "x-source": "openapi/gitlab-application-api-openapi.yml#/components/schemas/API_Entities_Appearance",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "pwa_name": {
      "type": "string"
    },
    "pwa_short_name": {
      "type": "string"
    },
    "pwa_description": {
      "type": "string"
    },
    "logo": {
      "type": "string"
    },
    "pwa_icon": {
      "type": "string"
    },
    "header_logo": {
      "type": "string"
    },
    "favicon": {
      "type": "string"
    },
    "new_project_guidelines": {
      "type": "string"
    },
    "profile_image_guidelines": {
      "type": "string"
    },
    "header_message": {
      "type": "string"
    },
    "footer_message": {
      "type": "string"
    },
    "message_background_color": {
      "type": "string"
    },
    "message_font_color": {
      "type": "string"
    },
    "email_header_and_footer_enabled": {
      "type": "string"
    }
  }
}

=== api-evangelist/gitlab/examples/gitlab-api-v4-application-api_entities_appearance-example.json
{
  "title": "example_value",
  "description": "Example description",
  "pwa_name": "Example Project",
  "pwa_short_name": "Example Project",
  "pwa_description": "Example description",
  "logo": "example_value",
  "pwa_icon": "example_value",
  "header_logo": "example_value",
  "favicon": "example_value",
  "new_project_guidelines": "example_value"
}
